djcrm/djcrm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include(('leads.urls','leads'), namespace="leads"))
]

djcrm/leads/urls.py
from django.contrib import admin
from django.urls import path

from .views import leads_list, lead_detail, lead_create

urlpatterns = [
    path('',leads_list, name='lead-list'),
    path('<int:pk>/', lead_detail, name='lead_detail'),
    # path('<int:pk>/update/', lead_update, name='lead_update'),
    # path('<int:pk>/delete/', lead_delete, name='lead_delete'),
    path('create/', lead_create, name='lead_create'),
]

djcrm/leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent",on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

djcrm/leads/forms.py
from django import forms
from .models import Lead

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent'
        )

djcrm/leads/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Lead
from .forms import LeadModelForm
from django.shortcuts import redirect

def leads_list(request):
    leads = Lead.objects.all()
    context = {"leads":leads}
    return render(request, "leads/leads_list.html", context)

def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead":lead
    }
    return render(request, "leads/lead_detail.html", context)

def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form":form
    }            
    return render(request,"leads/lead_create.html",context)

djcrm/leads/templates/leads/lead_create.html
{% extends "base.html" %}

{% block content %}
<a href="/leads">Go back to leads</a>
<hr/>
<h1>Create a new lead</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>
{% endblock content %}    

djcrm/leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% block content %}

<a href="{% url 'leads:lead-detail' lead.pk %}">Go back to {{ lead.first_name}} {{ lead.last_name}}</a>
<hr/>
<h1>Update lead: {{ lead.first_name}} {{ lead.last_name}}</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update</button>
</form>

{% endblock content %}

djcrm/leads/templates/leads/leads_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}

<body>
    <a href="{% url 'leads:lead_create' %}">Create a new lead</a>
    <hr/>
    <h1>This is all of our leads</h1>
    {% for lead in leads %}
    <div class="lead">
        <a href="{% url 'leads:lead_detail' lead.pk %}">{{lead.first_name}} {{lead.last_name}}</a>
    </div>
    {% endfor %}
{% endblock content %}

djcrm/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
    {% include 'scripts.html' %}

</body>
</html>

djcrm/templates/landing.html
{% extends 'base.html'%}
{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
      <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
        <img class="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      </div>
      <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM built with Django
        </h1>
        <p class="mb-8 leading-relaxed">
            This CRM helps you manage your leads.
        </p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

djcrm/templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-green-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Tailblocks</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a class="mr-5 hover:text-gray-900">Sign Up</a>
      </nav>
      <a href="#" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
    </a>
    </div>
  </header>

djcrm/templates/scripts.html
<script>
    console.log("Assalomu aleykum")
</script>